### ISSUE TITLE
Update to list of ECS frameworks

### ISSUE THREAD

**Issue by pmbittner** [SanderMertens/ecs-faq#9]
Hi SanderMertens,

Would you like to add my ECS to your list? It's entry would be

[Polypropylene](https://github.com/pmbittner/Polypropylene) (C++17, MIT)

Thank you and kind regards,
Paul

**Comment by SanderMertens** [comment]
Hi! I'm trying to only keep active projects (or projects that have been active) that at least have 50 stars (for lack of a better metric) in the list of ECS frameworks. Just checked in on your library again, and it looks like there have been no commits since January 14th!

Don't hesitate to reopen this issue once the project meets these criteria :)
